### ISSUE TITLE
Change the shell prompt as user navigate to a different page

### ISSUE THREAD

**Issue by khashf** [zzzanderw/zanderwork.com#1]
Looks like the shell prompt on the top menu bar doesn't change the current path when user navigate to a different page than the home page

**Comment by zzzanderw** [comment]
This is a great idea, but i have no idea how to implement this. I'd probably need to go muck around the forked version of the theme and do something to it. Maybe this summer...

**Comment by zzzanderw** [comment]
Also, it's actually the home button, so it kinda makes sense that it's constant? Not sure...

**Comment by khashf** [comment]
Oh that's right. Then maybe just remove the blinking cursor since it seems to hint user is standing there and about to type more. I think this one is easy to remove
